apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: apiserver
spec:
   containers:
   - name: apiserver1
     image: shareefmastan/postman:1.1
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: apiservice
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  selector:
    app: apiserver
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80

