apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkinsserver
spec:
   containers:
   - name: apiserver1
     image: jenkins/jenkins:lts
     ports:
     - containerPort: 8080
       name: tcpport
     - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: my-jenkins-service
  labels:
    app: jenkinsservice
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  selector:
    app: jenkinsserver
  type: LoadBalancer
  ports:
  - name: containerserviceport
    nodePort: 31100
    port: 8080
    targetPort: 8080
  - name: tcpport
    nodePort: 30100
    port: 50000
    targetPort: 50000
