apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  awsElasticBlockStore:
    volumeID: vol-07559cb7af3d6b385
    fsType: ext4
